version: '3.8'
services:
  composer:
    build:
      context: ./
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: composer

  tests_unit:
    build:
      context: ./
      dockerfile: docker/php-cli/Dockerfile
    env_file:
      - docker/.env.test
    volumes:
      - .:/app
    working_dir: /app
    restart: never
    entrypoint: vendor/bin/phpunit

  tests_acceptance:
    build:
      context: ./
      dockerfile: docker/php-cli/Dockerfile
    env_file:
      - docker/.env.test
    volumes:
      - .:/app
    working_dir: /app
    restart: never
    entrypoint: vendor/bin/behat
